 if (document.images) {
  arrow = new Image(); arrow.src = "images/arrow.png";
  arrow90 = new Image(); arrow90.src = "images/arrow90.png";
  }
  
  function hideShow(element){
    if((document.getElementById(element).style.display == 'none') || (document.getElementById(element).style.display == '')) {
      document.getElementById(element).style.display = 'block';
      if (document.images) {
        document.getElementById("arrow").src=arrow.src;
      }
    } else if(document.getElementById(element).style.display == 'block') {
      document.getElementById(element).style.display = 'none';
      if (document.images) {
        document.getElementById("arrow").src=arrow90.src;
      }
    }
  }
  
  function fill_example(){
      document.seq_form.seqs.value=">gi|452931731|gb|GAFI01011362.1|\n\
AGTTTTCGTGGGTGCATTTCAGAGTTTTCGTGGGTGCATTTCAGGGTTGTTCTTGTTG\
CAGATTTGGCCGTTTCCGTTTCGGCAAACGTAGCTCGTTAACCGGTTCTTTTGGTACC\
TGTAGCTTGGAGAATGTCAGTTACATTGGAAAGGACACAAACTTGAAAAATTACGATA\
AATCACGTCCAATCGTCTAGCCAGGACGACATGAATACAAGTCCCACTAACGAAAATG\
TCATGTTTAAGGAGAAAAAAGACTACAACATGACCATGGGATATTCCTACGATTCTCC\
TATAGAAACCACGACAGAGTTATAGATAGCATTCTTTCTCCATTAAATCATACTTCTT\
GTCCTAAATCAAATTGTAAATAGATATGGTTTCAACGGATTTAAATTACTTTATTATC\
TATGTGATATTCGGTGTACTTACTAGGTTTGTCACAACCATGCTCAAAATATTGCCCC\
CCTTTAGATAGGGCTTTCTTAACTAGAAAAAGTATACATTTATTAATAAATCCCATTA\
ACAAATTAGCTCACTGTGGCTTATAAATAAAGGTAAACCATTATATTTTATTAATTGT\
AGTGCCAAACTAAGTAAATTGAAAATTGATTTTGATTAGACCATAGTTTCCATTTTTA\
TGCTCACGATTTCAGCTACATGAGTACGTACAACGGAATCTGGGATATTGATTGCTAC\
TCAAAAACAGTTTTTATAGCGATGAACTATAAAAAAATGACCGAACTGACCGATTGAA\
TCATATGTCGGCTGCAGAAAGCGTATTTTGTGTAAATATCGTTTCTAAGCAATTAGAA\
TAATTCTACCTACGCATCTGTAAAATGTTTATTTAGCAACTAGCCTAAACTTGTAAAT\
ACTTTTGTAAAATAGCTTTGTAAAAATAACTTATTTTTACACGTTTTATACCTATCTT\
GCCAAAATAAAGTAAGTGTGC\n\
>gi|452932093|gb|GAFI01011000.1|\n\
ATTGGAAAGGACACAAACTTGAAAAATTACGATAAATCACGTCCAGTAAGTAATGAAT\
CTGCGTCGACAGTGCGAGCGTCTAGTGAAGACGATAACACTCATCTAATTAAAAGTAC\
TAACAATAACATAAGGAGAGATCATATTTACAGATCGTCTAGCCAGGACGACATGAAT\
ACAAGTCCCACTAACGAAAATGTCATGTTTAAGGAGAAAAAAGACTACAACATGACCA\
TGGGATATTCCTACGATTCTCCTATAGAAACCACGACAGAGTTATAGATAGCATTCTT\
TCTCCATTAAATCATACTTCTTGTCCTAAATCAAATTGTAAATAGATATGGTTTCAAC\
GGATTTAAATTACTTTATTATCTATGTGATATTCGGTGTACTTACTAGGTTTGTCACA\
ACCATGCTCAAAATATTGCCCCCCTTTAGATAGGGCTTTCTTAACTAGAAAAAGTATA\
CATTTATTAATAAATCCCATTAACAAATTAGCTCACTGTGGCTTATAAATAAAGGTAA\
ACCATTATATTTTATTAATTGTAGTGCCAAACTAAGTAAATTGAAAATTGATTTTGAT\
TAGACCATAGTTTCCATTTTTATGCTCACGATTTCAGCTACATGAGTACGTACAACGG\
AATCTGGGATATTGATTGCTACTCAAAAACAGTTTTTATAGCGATGAACTATAAAAAA\
ATGACCGAACTGACCGATTGAATCATATGTCGGCTGCAGAAAGCGTATTTTGTGTAAA\
TATCGTTTCTAAGCAATTAGAATAATTCTACCTACGCATCTGTAAAATGTTTATTTAG\
CAACTAGCCTAAACTTGTAAATACTTTTGTAAAATAGCTTTGTAAAAATAACTTATTT\
TTACACGTTTTATACCTATCTTGCCAAAATAAAGTAAGTGTGC\n\
>gi|452936189|gb|GAFI01006904.1|&42..623@TCOGS2:TC012899-PA\n\
GGGAGGAATATCTCGCGATTTCAGATTCGACAGGCCAAACCATGGAAGAAGAGGTGCA\
ATTGTTTATAAGAAGAGTGTCCAAGCTGGAGGGATTACTCAAGGAGCTGTACATGAAA\
TGCAATAGCACAGGCGACGGAAACGTAATCCTGCATTTGCTCGATAAATGCTCCAAGA\
TTTTGGATCGAGTGAATGGAGATAAATCTTTGAGCGCCGGAGGACGCTTCGAATGGGT\
CAATTCGATCCTGGTTAAATGCCTGCAAGAGGGATCTTGGCTGCTTGTCGACAATGTA\
AATCTATGCAGTGCGGCCGTTCTAGACCGATTGAATGCACTTTTGGAACCCAACGGCG\
TTCTCACTATATCGGAGCGGGGCGTCGATGATGATGGGAAAATGTTCGAAGTCAAACC\
ACATAAAGAGTTCCGGATATTTTTGACCATGGATCCGAAAAATGGTGAAATATCAAGA\
GCCATGCGAAACAGAGGTGTGGAAATTCACATGCTCAACTCCTCCGATGGTTCATCGC\
TCAACCAATACGACATCAAAAGCCTGATCGACCTGGAAGGTCTCTCCAACCCCAACCA\
TATAGCGGTTCTCCTCAAAGTCCACGAGTTTATATCAGGATTGAT\n\
>gi|452927117|gb|GAFI01015976.1|\n\
ATCCACGGGCATAATTAGAACGAAAAGAACTTTTGACTATATCAGCCAAGAAAGTCTA\
CCGTTTATTCTAATAGCTTGGGCAAGAGATAATCCGAATGCTACACGAGACTATTTCG\
AAACAAGCACTCAATTGGTGATTAATCTTATTGGTGACCAAAACAGACTTATTTTGGT\
AATTGGTGATGCAAAACCAAATATTGTGCAGAAAAAGCTGGGCGATATAGTGAAGATC\
ATCCAGGAACAATCTGGATTAATCGCAGGGATAGAAAAATTGGGCTCCCGACAATTTA\
TTGGCGGAAATGGGACTCTGGAAAACGACCCTGAAGGCACCGATGTGTGGTTTTATGT\
GATTGATCCAGACACTGACCAAATATTGACCAGAAATAGTTCGCTTGTTAAAAGTTCA\
GAGCGTTAATAGACAAATCATCTATGGACAACATAACATTCGACTTGACGGCACAAAT\
AAAACATACGGCTTTCAACATTCACGAGCCCCTGGTTTTCCATAAAGTCCGGACAGCT\
TCCCTGGCTTCGTTCAACGATGAAGTGTTTCTCTATGCCTTGATTATTATTGCCTGTA\
TCATATTTGTGCTGGGCAGTGTTGGCATTATTTATATCTGCGTTTCGTGGTCCAGATA\
TAAAAGCTTCAACGCTCAATTTACCAAGGCGCGGCAATATGTAGTGCCTGCCAGTCCA\
GCAAGATACGACACTGTGTATGTTGAACCCAACCTGAAGGAGTACGAGACGCAAGTCT\
TGCAAATGGTAGTGAATGTTGATGATCAAGAGGATTTTAATGATTTGCAAATCGACTT\
CAGCAACAAAAATCATGCATTTAGCTTGGAGAATGTCAGTTACATTGGAAAGGACACA\
AACTTGAAAAATTACGATAAATCACGTCCAATCGTCTAGCCAGGACGACATGAATACA\
AGTCCCACTAACGAAAATGTCATGTTTAAGGAGAAAAAAGACTACAACATGACCATGG\
GATATTCCTACGATTCTCCTATAGAAACCACGACAGAGTTATAGATAGCATTCTTTCT\
CCATTAAATCATACTTCTTGTCCTAAATCAAATTGTAAATAGATATGGTTTCAACGGA\
TTTAAATTACTTTATTATCTATGTGATATTCGGTGTACTTACTAGGTTTGTCACAACC\
ATGCTCAAAATATTGCCCCCCTTTAGATAGGGCTTTCTTAACTAGAAAAAGTATACAT\
TTATTAATAAATCCCATTAACAAATTAGCTCACTGTGGCTTATAAATAAAGGTAAACC\
ATTATATTTTATTAATTGTAGTGCCAAACTAAGTAAATTGAAAATTGATTTTGATTAG\
ACCATAGTTTCCATTTTTATGCTCACGATTTCAGCTACATGAGTACGTACAACGGAAT\
CTGGGATATTGATTGCTACTCAAAAACAGTTTTTATAGCGATGAACTATAAAAAAATG\
ACCGAACTGACCGATTGAATCATATGTCGGCTGCAGAAAGCGTATTTTGTGTAAATAT\
CGTTTCTAAGCAATTAGAATAATTCTACCTACGCATCTGTAAAATGTTTATTTAGCAA\
CTAGCCTAAACTTGTAAATACTTTTGTAAAATAGCTTTGTAAAAATAACTTATTTTTA\
CACGTTTTATACCTATCTTGCCAAAATAAAGTAAGTGTGC";
 document.getElementById("check").checked=true;
  }
  
  function on_help(page){
  if(page==1)
  {
  window.open("help.php?page=1","Online Help",'height=250,width=480');
  }else if(page==2){
  window.open("help.php?page=2","Online Help",'height=250,width=480');
  }else if(page==3){
  window.open("help.php?page=3","Online Help",'height=250,width=480');
  }else{
  window.open("help.php?page=4","Online Help",'height=250,width=480');
  }
  
  }
  
  function validateForm(){
  	  var ttext = document.forms["seq_form"]["seqs"].value;
  	  var tfile = document.forms["seq_form"]["seq_file"].value;
  	  var bfile = document.forms["seq_form"]["blastx_file"].value;
  	  var evalue = document.forms["seq_form"]["evalue"].value;
  	  var per = document.forms["seq_form"]["per"].value;
  	  var rate = document.forms["seq_form"]["rate"].value;
  	  var dist = document.forms["seq_form"]["dist"].value;
  	  if((ttext==null||ttext==""||/^\s+$/g.test(ttext)) && (tfile==null||tfile=="")){
  	  	  alert("Please input/upload transcriptome file!");
  	  	  return false;
  	  }
  	  if(evalue==""||per==""||rate==""||dist==""){
  	  	  alert("Please set the arguments!");
  	  	  return false;
  	  }
  	  if((bfile==null||bfile=="") && document.getElementById("check").checked==false){
  	  	  alert("Please upload BLASTX output file!");
  	  	  return false;
  	  }
  }
  
  
